FROM golang:1.14

ARG MDG_NAME

ENV MDG_NAME=$MDG_NAME \
    LOG_PATH=/go/src/log

WORKDIR /go/src/app

COPY graphs/ draco/main.go /

RUN go get -u github.com/project-draco/moea && \
    go build -o main main.go

ENTRYPOINT /usr/bin/time -o time/${MDG_NAME}.draco --append ./main < "+mdg+" > dot/"+mdg_name+".dot 2>> ${LOG_PATH}/output.txt