FROM bunch_base:latest

ARG EXPERIMENT_NAME
ENV EXPERIMENT_NAME=${EXPERIMENT_NAME}

WORKDIR ${BASE_PATH}

COPY script/run_bunch.sh src/Bunch-3.5.jar src/BunchAPITest.java ./

RUN javac -cp Bunch-3.5.jar BunchAPITest.java 

ENTRYPOINT bash run_bunch.sh --name ${EXPERIMENT_NAME}