FROM bunch_base:latest

ARG MDG_SIZE

ENV MDG_SIZE=${MDG_SIZE}

WORKDIR ${BASE_PATH}

COPY script/run_bunch.sh src/Bunch-3.5.jar src/BunchAPITest.java ./

RUN javac -cp Bunch-3.5.jar BunchAPITest.java 

ENTRYPOINT bash run_bunch.sh --size ${MDG_SIZE}