FROM draco_multi_base:latest

ARG EXPERIMENT_NAME
ENV EXPERIMENT_NAME=${EXPERIMENT_NAME}

WORKDIR ${BASE_PATH}

COPY script/run_draco_multi.sh src/main.go ./


RUN go build -o main main.go

ENTRYPOINT bash run_draco_multi.sh --name ${EXPERIMENT_NAME}