FROM golang:1.14

ENV BASE_PATH=/go/src/app \
    EXP_PATH=/go/src/exp \
    LOG_PATH=/go/src/log \
    DATA_PATH=/go/src/data

RUN go get -u github.com/project-draco/moea && \
    apt-get update -y && \
    apt-get install -y time
