FROM draco_base:latest

ARG MDG_SIZE

ENV MDG_SIZE=${MDG_SIZE}

WORKDIR ${BASE_PATH}

COPY script/run_draco.sh src/main.go ./

RUN go build -o main main.go

ENTRYPOINT bash run_draco.sh --size ${MDG_SIZE}